import React from 'react';
import Card from '@material-ui/core/Card';
import CardHeader from '@material-ui/core/CardHeader';
import CardContent from '@material-ui/core/CardContent';
import CardActions from '@material-ui/core/CardActions';
import Avatar from '@material-ui/core/Avatar';
import IconButton from '@material-ui/core/IconButton';
import { CardWithCommentTypes } from './CardWithComment.props';

/**
 * CardWithComment is generated by Webcodesk. Replace this comment with a valuable description.
 */
class CardWithComment extends React.Component {
  componentDidUpdate(prevProps, prevState, snapshot) {
  }

  // handleButtonClick = e => {
  //   if (e) {
  //     e.stopPropagation();
  //     e.preventDefault();
  //   }
  //   this.props.onSubmit({
  //     enteredText: this.state.localInputText
  //   });
  // };

  render() {
    const { data, cells } = this.props;
    return (
      <Card>
        <CardHeader
          avatar={
            <Avatar aria-label="comment-avatar">
              A
            </Avatar>
          }
          action={
            <IconButton>

            </IconButton>
          }
          title="Commented by Alex"
          subheader="two days ago"
        >
        </CardHeader>
      </Card>

    );
  }
}

CardWithComment.propTypes = CardWithCommentTypes;

CardWithComment.defaultProps = {
  onSubmit: () => {
    console.info('CardWithComment.onSubmit is not set');
  }
};

export default CardWithComment;
