/**
 * This function is generated by Webcodesk. Replace this comment with a valuable description.
 *
 * @functionTypes {SampleFunctionTypes from ./LogicPrimitives.props.js}
 */
export const sampleFunction = options => dispatch => {
  // do something here with options;
  const { text, extraOptions } = options;
  // and pass them forward to the dispatcher
  const dispatchOptions = {
    text,
    extraOptions: {
      extraFlag: extraOptions.extraFlag
    }
  };
  dispatch('optionsFromInput', dispatchOptions);
};
