const variableStorage = {};

/**
 * This function is generated by Webcodesk. Replace this comment with a valuable description.
 *
 * @functionTypes {StoreVariableTypes from ./VariableStorage.props}
 */
export const storeVariable = options => dispatch => {
  const { name, value } = options;
  variableStorage[name] = { ...variableStorage[name], ...value };
  dispatch('success');
};

/**
 * Retrieves the variables from the variable storage.
 *
 * @functionTypes {GetVariablesTypes from ./VariableStorage.props}
 */
export const getVariables = names => dispatch => {
  const result = {};
  if (names && names.length > 0) {
    for (let i = 0; i < names.length; i++) {
      result[names[i]] = variableStorage[names[i]];
    }
  }
  dispatch('variablesMap', result);
};