/**
 * This function is generated by Webcodesk. Replace this comment with a valuable description.
 *
 * @functionTypes {SetDrawerTypes from ./PageFrameWithDrawer.props.js}
 */
// export const setDrawer = () => dispatch => {
//   dispatch({
//     close: false,
//     open: true,
//   });
// };
