import get from 'lodash/get';
import set from 'lodash/set';

/**
 * This function is generated by Webcodesk. Replace this comment with a valuable description.
 *
 * @functionTypes {SetPageFrameTitleTextTypes from ./props/PageFrameWithDrawer.props.js}
 */
export const setPageFrameTitleText = ({text}, state) => dispatch => {
  if (state) {
    set(state, 'properties.properties.top.title.text', text);
    dispatch({properties: get(state, 'properties.properties')});
  }
};

/**
 * This function is generated by Webcodesk. Replace this comment with a valuable description.
 *
 * @functionTypes {ClosePageFrameDrawerTypes from ./props/PageFrameWithDrawer.props.js}
 */
export const closePageFrameDrawer = (options, state) => dispatch => {
  if (state) {
    set(state, 'properties.properties.left.drawer.open', false);
    dispatch({properties: get(state, 'properties.properties')});
  }
};
