/**
 * This function is generated by Webcodesk. Replace this comment with a valuable description.
 *
 * @functionTypes {SetActiveTopNavigationByIdTypes from ./props/TopNavigation.props.js}
 */
export const setActiveTopNavigationById = ({id}, properties) => dispatch => {
  console.info('Properties: ', properties);
  if (id && properties) {
    const topNavigationItems = properties.items;
    if (topNavigationItems && topNavigationItems.length > 0) {
      for (let i = 0; i < topNavigationItems.length; i++) {
        topNavigationItems[i].active = topNavigationItems[i].id === id;
      }
    }
    dispatch({properties});
  }
};
